// <auto-generated />
using FAQProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQProject.Migrations
{
    [DbContext(typeof(FaqsContext))]
    [Migration("20250929051135_DbCreation")]
    partial class DbCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQProject.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "gen",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("FAQProject.Models.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FAQId = 1,
                            Answer = "ASP.NET Core is a free and open-source web framework developed by Microsoft for building modern, cloud-based, and internet-connected applications.",
                            CategoryId = "gen",
                            Question = "What is ASP.NET Core?",
                            TopicId = "asp"
                        },
                        new
                        {
                            FAQId = 2,
                            Answer = "Blazor is a framework for building interactive client-side web UIs with .NET. It allows developers to use C# instead of JavaScript for web development.",
                            CategoryId = "gen",
                            Question = "What is Blazor?",
                            TopicId = "blz"
                        },
                        new
                        {
                            FAQId = 3,
                            Answer = "Entity Framework (EF) is an object-relational mapper (ORM) for .NET that enables developers to work with databases using .NET objects, reducing the need for direct SQL.",
                            CategoryId = "gen",
                            Question = "What is Entity Framework?",
                            TopicId = "ef"
                        },
                        new
                        {
                            FAQId = 4,
                            Answer = "ASP.NET Core was first released in 2016 as the successor to ASP.NET, designed for cross-platform development.",
                            CategoryId = "hist",
                            Question = "When was ASP.NET Core released?",
                            TopicId = "asp"
                        },
                        new
                        {
                            FAQId = 5,
                            Answer = "Blazor was introduced by Microsoft in 2018 as part of the ASP.NET family of technologies.",
                            CategoryId = "hist",
                            Question = "When was Blazor introduced?",
                            TopicId = "blz"
                        },
                        new
                        {
                            FAQId = 6,
                            Answer = "Entity Framework was first released in 2008 as part of .NET Framework 3.5 Service Pack 1.",
                            CategoryId = "hist",
                            Question = "When was Entity Framework first released?",
                            TopicId = "ef"
                        });
                });

            modelBuilder.Entity("FAQProject.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "asp",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            TopicId = "blz",
                            Name = "Blazor"
                        },
                        new
                        {
                            TopicId = "ef",
                            Name = "Entity Framework"
                        });
                });

            modelBuilder.Entity("FAQProject.Models.FAQ", b =>
                {
                    b.HasOne("FAQProject.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQProject.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
