// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummitV2.Data;

#nullable disable

namespace SummitV2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124035857_EnableCascadeDelete")]
    partial class EnableCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanId"));

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClanId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Clans");

                    b.HasData(
                        new
                        {
                            ClanId = 1,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 7, 27, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4709),
                            Description = "Veteran Guardians specializing in endgame PVE content.",
                            Name = "Astral Vanguard"
                        },
                        new
                        {
                            ClanId = 2,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 8, 18, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4716),
                            Description = "Competitive PVP players who love Trials and Iron Banner.",
                            Name = "Iron Wolves"
                        },
                        new
                        {
                            ClanId = 3,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 8, 26, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4717),
                            Description = "Late-night Guardians focusing on Gambit, Dungeons, and seasonal grinds.",
                            Name = "Shadow Syndicate"
                        },
                        new
                        {
                            ClanId = 4,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 8, 31, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4718),
                            Description = "New player–friendly clan helping Guardians level up and learn the game.",
                            Name = "Lightbearer Legion"
                        },
                        new
                        {
                            ClanId = 5,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 9, 15, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4719),
                            Description = "Sherpas assisting Guardians with raids, triumphs, and exotic missions.",
                            Name = "The Last City Watch"
                        },
                        new
                        {
                            ClanId = 6,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 9, 20, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4720),
                            Description = "High-end raiding group completing flawless and master raids.",
                            Name = "Vanguard Elite"
                        },
                        new
                        {
                            ClanId = 7,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 9, 30, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4721),
                            Description = "Chaotic Gambit lovers who thrive in the fog of war.",
                            Name = "The Drifter’s Crew"
                        },
                        new
                        {
                            ClanId = 8,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 10, 13, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4722),
                            Description = "Solo-focused players that team up for Nightfalls and seasonal missions.",
                            Name = "Eclipse Wardens"
                        },
                        new
                        {
                            ClanId = 9,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 10, 25, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4723),
                            Description = "Relaxed PVE clan that does raids, dungeons, and chill runs.",
                            Name = "Nova Outriders"
                        },
                        new
                        {
                            ClanId = 10,
                            CreatedByUserId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            CreatedDate = new DateTime(2025, 11, 9, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4724),
                            Description = "Lore-obsessed Guardians diving deep into every mystery of the Traveler.",
                            Name = "The Infinite Chorus"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SummitV2.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("ClanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("ClanId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            ClanId = 1,
                            Description = "Full raid run with optional red border farming.",
                            EventDate = new DateTime(2025, 11, 27, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4804),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Deep Stone Crypt Raid"
                        },
                        new
                        {
                            EventId = 2,
                            ClanId = 1,
                            Description = "Grandmaster Nightfall — anti-champion mods required.",
                            EventDate = new DateTime(2025, 11, 30, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4806),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "GM Nightfall: The Corrupted"
                        },
                        new
                        {
                            EventId = 3,
                            ClanId = 2,
                            Description = "Casual PvP night. Stack in fireteams for faster matches.",
                            EventDate = new DateTime(2025, 11, 26, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4807),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Iron Banner Clash Night"
                        },
                        new
                        {
                            EventId = 4,
                            ClanId = 3,
                            Description = "3-hour Gambit session. No rage quitting.",
                            EventDate = new DateTime(2025, 11, 28, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4808),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Gambit Prime Marathon"
                        },
                        new
                        {
                            EventId = 5,
                            ClanId = 3,
                            Description = "Armor roll farming and Xenophage help.",
                            EventDate = new DateTime(2025, 12, 3, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4809),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Dungeon Farm: Pit of Heresy"
                        },
                        new
                        {
                            EventId = 6,
                            ClanId = 4,
                            Description = "Helping new Guardians unlock subclasses and find gear.",
                            EventDate = new DateTime(2025, 11, 25, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4810),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "New Light Onboarding Night"
                        },
                        new
                        {
                            EventId = 7,
                            ClanId = 5,
                            Description = "Challenge rotation and loot optimization.",
                            EventDate = new DateTime(2025, 11, 29, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4811),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "King’s Fall Challenge Mode"
                        },
                        new
                        {
                            EventId = 8,
                            ClanId = 6,
                            Description = "Master difficulty raid clearing with coordinated builds.",
                            EventDate = new DateTime(2025, 12, 4, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4812),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Root of Nightmares Master Mode"
                        },
                        new
                        {
                            EventId = 9,
                            ClanId = 7,
                            Description = "Complete seasonal Gambit challenges for resets.",
                            EventDate = new DateTime(2025, 12, 1, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4813),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Seasonal Gambit Reset Run"
                        },
                        new
                        {
                            EventId = 10,
                            ClanId = 8,
                            Description = "Power grind via Nightfall rotation runs.",
                            EventDate = new DateTime(2025, 11, 27, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4814),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Weekly Nightfall Marathon"
                        },
                        new
                        {
                            EventId = 11,
                            ClanId = 9,
                            Description = "Engram farming and seasonal vendor focusing.",
                            EventDate = new DateTime(2025, 12, 3, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4815),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Seasonal Activity Grind"
                        },
                        new
                        {
                            EventId = 12,
                            ClanId = 10,
                            Description = "Deep-dive into Witness influence and the Collapse.",
                            EventDate = new DateTime(2025, 11, 30, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4816),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Lore Discussion Night"
                        },
                        new
                        {
                            EventId = 13,
                            ClanId = 2,
                            Description = "Warm-up scrims and loadout tuning for Trials weekend.",
                            EventDate = new DateTime(2025, 12, 5, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4817),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Trials Warmup"
                        },
                        new
                        {
                            EventId = 14,
                            ClanId = 4,
                            Description = "Teaching new players how to build subclasses efficiently.",
                            EventDate = new DateTime(2025, 12, 8, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4818),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Subclass Build Workshop"
                        },
                        new
                        {
                            EventId = 15,
                            ClanId = 8,
                            Description = "Chill playlist grinding for vendor rewards.",
                            EventDate = new DateTime(2025, 12, 6, 3, 58, 57, 383, DateTimeKind.Utc).AddTicks(4819),
                            OrganizerId = "17f1e219-9a92-4b7a-85b8-e3f3e2f3b450",
                            Title = "Vanguard Ops Playlist Night"
                        });
                });

            modelBuilder.Entity("SummitV2.Models.UserClan", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "ClanId");

                    b.HasIndex("ClanId");

                    b.ToTable("UserClans");
                });

            modelBuilder.Entity("SummitV2.Models.UserEvent", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("SummitV2.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Clan", b =>
                {
                    b.HasOne("SummitV2.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Clans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SummitV2.Models.Event", b =>
                {
                    b.HasOne("Clan", "Clan")
                        .WithMany("Events")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SummitV2.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("SummitV2.Models.UserClan", b =>
                {
                    b.HasOne("Clan", "Clan")
                        .WithMany("UserClans")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SummitV2.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserClans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("SummitV2.Models.UserEvent", b =>
                {
                    b.HasOne("SummitV2.Models.Event", "Event")
                        .WithMany("UserEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SummitV2.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Clan", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UserClans");
                });

            modelBuilder.Entity("SummitV2.Models.Event", b =>
                {
                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("SummitV2.Models.ApplicationUser", b =>
                {
                    b.Navigation("Clans");

                    b.Navigation("Events");

                    b.Navigation("UserClans");

                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
