// <auto-generated />
using HOT2Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT2Project.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT2Project.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "E",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = "C",
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = "F",
                            Name = "Furniture"
                        },
                        new
                        {
                            CategoryId = "B",
                            Name = "Books"
                        },
                        new
                        {
                            CategoryId = "T",
                            Name = "Toys"
                        },
                        new
                        {
                            CategoryId = "H",
                            Name = "Home Appliances"
                        },
                        new
                        {
                            CategoryId = "S",
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("HOT2Project.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductDescLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = "S",
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "AeroFlo ATB Wheels",
                            ProductPrice = 189m,
                            ProductQty = 40
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = "C",
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Clear Shade 85-T Glasses",
                            ProductPrice = 45m,
                            ProductQty = 14
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = "S",
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Cosmic Elite Road Warrior Wheels",
                            ProductPrice = 165m,
                            ProductQty = 22
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = "S",
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Cycle-Doc Pro Repair Stand",
                            ProductPrice = 166m,
                            ProductQty = 12
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = "S",
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Dog Ear Aero-Flow Floor Pump",
                            ProductPrice = 5m,
                            ProductQty = 25
                        });
                });

            modelBuilder.Entity("HOT2Project.Models.Product", b =>
                {
                    b.HasOne("HOT2Project.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
