// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummitWeb.Models;

#nullable disable

namespace SummitWeb.Migrations
{
    [DbContext(typeof(SummitContext))]
    partial class SummitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SummitWeb.Models.Clan", b =>
                {
                    b.Property<int>("ClanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClanId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClanId");

                    b.ToTable("Clans");

                    b.HasData(
                        new
                        {
                            ClanId = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A clan for destiny players who like raiding.",
                            Name = "Raiders"
                        },
                        new
                        {
                            ClanId = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "PvP-focused clan for Guardians who live in the Crucible.",
                            Name = "Crucible Masters"
                        },
                        new
                        {
                            ClanId = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clan for those who love Gambit and banking motes.",
                            Name = "Gambit Crew"
                        },
                        new
                        {
                            ClanId = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dedicated to weekly Nightfalls and high difficulty strikes.",
                            Name = "Nightfall Heroes"
                        },
                        new
                        {
                            ClanId = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Top-tier Guardians focused on Trials of Osiris.",
                            Name = "Trials Legends"
                        },
                        new
                        {
                            ClanId = 6,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A chill group for casual players of all levels.",
                            Name = "Casual Guardians"
                        },
                        new
                        {
                            ClanId = 7,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clan for players who love the story and lore of Destiny.",
                            Name = "Lore Seekers"
                        },
                        new
                        {
                            ClanId = 8,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Focused on helping members collect exotic gear.",
                            Name = "Exotic Hunters"
                        },
                        new
                        {
                            ClanId = 9,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clan specializing in Iron Banner events.",
                            Name = "Iron Banner Lords"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
