// <auto-generated />
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20250922225134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryId = 1,
                            Email = "Email@example.com",
                            Firstname = "Jane",
                            Lastname = "Doe",
                            Phone = "123-456-1234"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryId = 2,
                            Email = "john.smith@example.com",
                            Firstname = "John",
                            Lastname = "Smith",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryId = 1,
                            Email = "emily.clark@example.com",
                            Firstname = "Emily",
                            Lastname = "Clark",
                            Phone = "555-333-4444"
                        },
                        new
                        {
                            ContactId = 4,
                            CategoryId = 3,
                            Email = "michael.brown@example.com",
                            Firstname = "Michael",
                            Lastname = "Brown",
                            Phone = "555-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
